name: Deploy FastAPI to AWS EKS

on:
  push:
    branches:
      - main  # Runs when changes are pushed to `main`
  workflow_dispatch:  # Allows manual trigger

jobs:
  # # -------------------------- #
  # # Run Unit Tests
  # # -------------------------- #
  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v4

  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.10'  # Change to match your Python version

  #   - name: Install System Dependencies
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install -y build-essential python3-dev libssl-dev libffi-dev rustc

  #   - name: Install Dependencies
  #     run: |
  #       python -m pip install --upgrade pip setuptools wheel
  #       pip install -r requirements.txt
  #       pip install pytest httpx pytest-asyncio

  #   - name: Set Environment Variables
  #     run: |
  #       echo "DATABASE_URL=postgresql://user:password@postgres-service:5432/testdb" >> $GITHUB_ENV

  #   - name: Set PYTHONPATH
  #     run: echo "PYTHONPATH=${PYTHONPATH}:$(pwd)" >> $GITHUB_ENV

  #   - name: Run Tests
  #     run: pytest --asyncio-mode=auto || exit 1

  # -------------------------- #
  # Build & Push Docker Image
  # -------------------------- #
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    # needs: test

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: ecr-login
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build & Push Docker Image
      run: |
        IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest"
        docker build -t $IMAGE_URI -f Dockerfile .
        docker push $IMAGE_URI

    outputs:
      image_uri: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

  # -------------------------- #
  # Deploy to Kubernetes EKS
  # -------------------------- #
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build  # This job depends on `build` completion

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Kubeconfig
      run: |
        mkdir -p ~/.kube
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Verify Kubeconfig Contexts
      run: kubectl config get-contexts

    - name: Create ECR ImagePullSecret
      run: |
        kubectl create secret docker-registry ecr-secret \
          --docker-server=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com \
          --docker-username=AWS \
          --docker-password=$(aws ecr get-login-password --region ${{ secrets.AWS_REGION }}) \
          --dry-run=client -o yaml | kubectl apply -f -


    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/postgres.yaml

    - name: Verify Deployment
      run: kubectl get pods -n default
